routes/web.php
<?php

use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PenjualanController;
use App\Http\Controllers\PembelianController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TransaksiController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('Dashboard');
});

Route::resource('product', 'ProductController');
Route::resource('category', 'CategoryController');

Route::get('/discount', 'DiscountController@index');
Route::get('/discount/create', 'DiscountController@create');
Route::post('/discount', 'DiscountController@store');
Route::get('/discount/{discount}/edit', 'DiscountController@edit');
Route::patch('/discount/{discount}', 'DiscountController@update');
Route::delete('/discount/{id}', 'DiscountController@delete');

Route::get('/order', 'OrderController@index');

Route::get('/penjualan', 'PenjualanController@index');

//Bagian Pembelian
Route::resource('pembelian', 'PembelianController');

// Bagian Laporan
Route::resource('laporan', 'LaporanController');

// Bagian User
Route::resource('user', 'UserController');


Route::get('/transaksi', 'TransaksiController@index');
Route::get('/transaksi/create', 'TransaksiController@create');
Route::post('/transaksi', 'TransaksiController@store');
Route::get('/transaksi/{transaksi}/edit', 'TransaksiController@edit');
Route::patch('/transaksi/{transaksi}', 'TransaksiController@update');
Route::delete('/transaksi/{id}', 'TransaksiController@delete');

app/user.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class user extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'name', 'email', 'password','contact','address','level',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\user;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class UserController extends Controller
{
    public function index()
    {
        $user = user::all();
        $user = $user->groupBy('level');
        return view('user.index',compact('user'));
    }

    public function create()
    {
        return view('user.add');
    }

    public function store(Request $request)
    {
        $this->validate($request,
        [
            'name' => 'required',
            'email' => 'required|string|email|max:255|unique:users|confirmed',
            'password' => 'required|string|min:8|confirmed',
            'address' => 'required',
            'contact' => 'required',
            'level' => 'required'
        ]);

        $user = user::create([
            'name'      => $request->name,
            'email'     => $request->email,
            'password'  => Hash::make($request->password),
            'address'   => $request->address,
            'contact'   => $request->contact,
            'level'     => $request->level
        ]);
        if($user){
            //Berhasil
            return redirect()->route('user.index')->with(['success' => 'User Berhasil Ditambahkan!']);
        }else{
            //Gagal
            return redirect()->route('user.index')->with(['error' => 'User Gagal Ditambahkan!']);
        }
        

        // MAJID36 
        // KALO UDAH ADA ROLE / PE LEVELAN NTAR KU LANJUTIN DAN MAKE YG INI --MAJID36
        /*
        if ($request->level == '1') {
            $count1 = 1::where('email', $request->email)->count();
            $id1 = 1::where('email', $request->email)->get();
            foreach ($id1 as $val) {
                $1 = 1::findforfail($val->id);
            }
            if
        }
        */
        
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        return view('user.edit',compact('user'));
    }

    public function update(Request $request, user $user)
    {
        $this->validate($request,
        [
            'name' => 'required',
            'email' => 'required|string|email|max:255|unique:users|confirmed',
            'password' => 'required|string|min:8|confirmed',
            'address' => 'required',
            'contact' => 'required',
            'level' => 'required'
        ]);

        $user->update([
            'name'      => $request->name,
            'email'     => $request->email,
            'password'  => Hash::make($request->password),
            'address'   => $request->address,
            'contact'   => $request->contact,
            'level'     => $request->level
        ]);

        if($user){
            //Berhasil
            return redirect()->route('user.index')->with(['success' => 'Data User Berhasil Diperbarui!']);
        }else{
            return redirect()->route('user.index')->with(['error' => 'Data User Gagal Diperbarui!']);
        }
    }

    public function destroy($id)
    {
        $user = user::findOrFail($id);
        $user->delete();
        return redirect()->route('user.index');
    }
}

resources/views/user/add.blade.php
@extends('layouts.app')
@section('title','User | Tambah User')
@section('content')

<div class="section-body">
    <div class="section-header">
        <h1>User</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="{{ route('user.index') }}">User</a></div>
            <div class="breadcrumb-item active"><a>Tambah User</a></div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>Tambah User</h4>
                </div>
                <form action="{{ route('user.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama Lengkap</label>
                        <div class="col-sm-12 col-md-7">
                            <input type="text" name="name" placeholder="Isikan nama lengkap anda" class="form-control @error('name') is-invalid @enderror">
                            @error('name')
                            <div class="invalid-feedback p-2 shadow-sm rounded mt-2">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Level User</label>
                        <div class="col-sm-12 col-md-7">
                            <select name="level" class="form-control selectric @error('level') is-invalid @enderror">
                            @error('level')
                            <div class="invalid-feedback p-2 shadow-sm rounded mt-2">
                                {{ $message }}
                            </div>
                            @enderror
                            <option value="" disabled selected>Pilih Level User</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Email</label>
                        <div class="col-sm-12 col-md-7">
                            <input id="email" type="email" name="email" placeholder="Isikan email anda" autocomplete="new-email" class="form-control @error('email') is-invalid @enderror">
                            @error('email')
                            <div class="invalid-feedback p-2 shadow-sm rounded mt-2">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Konfirmasi Email</label>
                        <div class="col-sm-12 col-md-7">
                            <input id="email-confirm" type="email" name="email_confirmation" placeholder="Masukkan email anda kembali" autocomplete="new-email" class="form-control @error('email') is-invalid @enderror">
                            @error('email')
                            <div class="invalid-feedback p-2 shadow-sm rounded mt-2">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Password</label>
                        <div class="col-sm-12 col-md-7">
                            <input id="password" type="password" name="password" placeholder="Minimal 8 karakter" autocomplete="new-password" class="form-control @error('password') is-invalid @enderror">
                            @error('password')
                            <div class="invalid-feedback p-2 shadow-sm rounded mt-2">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Konfirmasi Password</label>
                        <div class="col-sm-12 col-md-7">
                            <input id="password-confirm" type="password" name="password_confirmation" placeholder="Masukkan password anda kembali" autocomplete="new-password" class="form-control @error('password') is-invalid @enderror">
                            @error('password')
                            <div class="invalid-feedback p-2 shadow-sm rounded mt-2">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">No HP</label>
                        <div class="col-sm-12 col-md-7">
                            <input type="numeric" name="contact" placeholder="Isikan hanya angka" class="form-control @error('contact') is-invalid @enderror">
                            @error('contact')
                            <div class="invalid-feedback p-2 shadow-sm rounded mt-2">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Alamat</label>
                        <div class="col-sm-12 col-md-7">
                            <textarea name="address" class="form-control @error('address') is-invalid @enderror"></textarea>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                        <div class="col-sm-12 col-md-7">
                            <a href="{{ route('user.index') }}" class="btn btn-danger">Cancel</a>
                            <button type="submit" class="btn btn-primary">Add</button>
                        </div>
                    </div>
                </form>
            </div>        
        </div>
    </div>
</div>

@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')
@section('title','User | Edit Data')
@section('content')

<div class="section-body">
    <div class="section-header">
        <h1>User</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="{{ route('user.index') }}">User</a></div>
            <div class="breadcrumb-item active"><a>Edit Data User</a></div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>Edit Data User</h4>
                </div>
                <form action="{{ route('user.update',$user->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                    <div class="card-body">
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama Lengkap</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="text" name="name" value="{{ $user->name }}" class="form-control @error('name') is-invalid @enderror">
                                @error('name')
                                <div class="bg-red-400 p-2 shadow-sm rounded mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Level User</label>
                            <div class="col-sm-12 col-md-7">
                                <select name="level" class="form-control selectric @error('level') is-invalid @enderror">
                                    @error('level')
                                    <div class="invalid-feedback p-2 shadow-sm rounded mt-2">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                    <option value="" disabled selected>Pilih Level User</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Email</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="email" name="email" value="{{ $user->email }}" class="form-control @error('email') is-invalid @enderror">
                                @error('email')
                                <div class="bg-red-400 p-2 shadow-sm rounded mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Passsword</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="password" name="password" value="{{ $user->password }}" class="form-control @error('password') is-invalid @enderror">
                                @error('password')
                                <div class="bg-red-400 p-2 shadow-sm rounded mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">No HP</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="numeric" name="contact" value="{{ $user->contact }}" class="form-control @error('contact') is-invalid @enderror">
                                @error('contact')
                                <div class="bg-red-400 p-2 shadow-sm rounded mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Alamat</label>
                            <div class="col-sm-12 col-md-7">
                                <textarea name="address" class="form-control">{{ $user->address }}</textarea>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <a href="{{ route('user.index') }}" class="btn btn-danger">Cancel</a>
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/user/index.blade.php
@extends('layouts.app')
@section('title','User | Data User')
@section('content')

<div class="section-body">
    @if (session('status'))
        <div class="alert">
            {{ session('status') }}
        </div>
    @endif
    
    <div class="card">
        <div class="card-header">
            <h4>Data User</h4>
            <div class="card-header-action">
                <a href="{{ route('user.create') }}" class="btn btn-primary">Tambah User</a>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-md" id="table-2">
                    <thead class="thead-light">
                        <tr>
                            <th width="100px">No.</th>
                            <th width="200px" style="text-align: center">Nama</th>
                            <th width="100px" style="text-align: center">Level</th>
                            <th style="text-align: center">Alamat</th>
                            <th style="text-align: center">No HP</th>
                            <th style="text-align: center">Email</th>
                            <th style="text-align: center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($user as $user)
                        <tr>
                            <td width="100px">{{ $loop->iteration }}</td>
                            <td width="200px" style="text-align: center">{{ $user->name }}</td>
                            <td width="100px" style="text-align: center">{{ $user->level }}</td>
                            <td width="500px">{{ $user->address }}</td>
                            <td width="200px" style="text-align: center">{{ $user->contact }}</td>
                            <td width="200px" style="text-align: center">{{ $user->email }}</td>
                            <td style="text-align: center">
                                <form action="{{ route('user.destroy',$user->id) }}" method="POST">
                                    <a href="{{ route ('user.edit' , $user->id) }}"
                                        class="btn btn-primary btn-action mr-1" data-toggle="tooltip"
                                        title="Edit"><i class="fas fa-pencil-alt"></i></a>
                                    @csrf
                                    @method('DELETE')

                                    <button type="submit"
                                        class="btn btn-danger btn-action mr-1"
                                        onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')" ><i title="Hapus" class="fas fa-trash"></i></button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection