routes/web.php
<?php

use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PenjualanController;
use App\Http\Controllers\PembelianController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TransaksiController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('Dashboard');
});

Route::resource('product', 'ProductController');
Route::resource('category', 'CategoryController');

Route::get('/discount', 'DiscountController@index');
Route::get('/discount/create', 'DiscountController@create');
Route::post('/discount', 'DiscountController@store');
Route::get('/discount/{discount}/edit', 'DiscountController@edit');
Route::patch('/discount/{discount}', 'DiscountController@update');
Route::delete('/discount/{id}', 'DiscountController@delete');

Route::get('/order', 'OrderController@index');

Route::get('/penjualan', 'PenjualanController@index');

//Bagian Pembelian
Route::resource('pembelian', 'PembelianController');

// Bagian Laporan
Route::resource('laporan', 'LaporanController');

// Bagian User
Route::resource('user', 'UserController');


Route::get('/transaksi', 'TransaksiController@index');
Route::get('/transaksi/create', 'TransaksiController@create');
Route::post('/transaksi', 'TransaksiController@store');
Route::get('/transaksi/{transaksi}/edit', 'TransaksiController@edit');
Route::patch('/transaksi/{transaksi}', 'TransaksiController@update');
Route::delete('/transaksi/{id}', 'TransaksiController@delete');

app/product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class product extends Model
{
    protected $fillable = ['name','image','categories_id','price','description','status','show'];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\category;
use App\product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products=product::all();
        return view('products.index',compact('products'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = category::get();
        return view('products.tambah')->with('categories',$categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'image' =>'required|image|mimes:png,jpg,jpeg',
            'description' => 'required',
            'price' => 'required|integer',
        ]);
        //image upload
        $image = $request->file('image');
        $imageName = date('YmdHis').'.'.$image->getClientOriginalExtension();
        $destination = storage_path('app/public/products');
        $image->move($destination, $imageName);

        if($request->status == 'on'){
            $status='ready';
        }else{
            $status='sold';
        }
        if($request->show == 'on'){
            $show='ya';
        }else{
            $show='tidak';
        }

        $product = product::create([
            'name'              => $request->name,
            'image'             => $imageName,
            'categories_id'     => $request->category,
            'description'       => $request->description,
            'price'             => $request->price,
            'status'            => $status,
            'show'              => $show,
        ]);
        if($product){
            //redirect dengan pesan sukses
            return redirect()->route('product.index')->with(['success' => 'Data Berhasil Disimpan!']);
        }else{
            //redirect dengan pesan error
            return redirect()->route('product.index')->with(['error' => 'Data Gagal Disimpan!']);
        };
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(product $product)
    {
        $categories = category::get();
        return view('products.edit', compact('product'))->with('categories',$categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, product $product)
    {
         $this->validate($request, [
            'name' => 'required',
            'category' => 'required',
            'image' =>'required|image|mimes:png,jpg,jpeg',
            'description' => 'required',
            'price' => 'required|integer',
        ]);

        $product = product::findorFail($product->id);

        if($request->status == 'on'){
            $status='ready';
        }else{
            $status='sold';
        }
        if($request->show == 'on'){
            $show='ya';
        }else{
            $show='tidak';
        }

        if ($request->file('image')== "") {
            $product->update([
            'name'              => $request->name,
            'categories_id'     => $request->category,
            'description'       => $request->description,
            'price'             => $request->price,
            'status'            => $status,
            'show'              => $show,
        ]);
        }else {
           Storage::disk('local')->delete('public/products/'.$product->image);
           //image upload
           $image = $request->file('image');
           $imageName = date('YmdHis').'.'.$image->getClientOriginalExtension();
           $destination = storage_path('app/public/products');
           $image->move($destination, $imageName);
            $product->update([
            'name'              => $request->name,
            'image'             => $imageName,
            'categories_id'     => $request->category,
            'description'       => $request->description,
            'price'             => $request->price,
            'status'            => $status,
            'show'              => $show,
            ]);
        }

        if($product){
            //redirect dengan pesan sukses
            return redirect()->route('product.index')->with(['success' => 'Data Berhasil Disimpan!']);
        }else{
            //redirect dengan pesan error
            return redirect()->route('product.index')->with(['error' => 'Data Gagal Disimpan!']);
        };
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = product::findOrFail($id);
        Storage::disk('local')->delete('public/products'.$product->image);
        $product->delete();
        return redirect()->route('product.index');
    }
}

resources/views/products/edit.blade.php
@extends('layouts.app')
@section('title','Products | Edit')
@section('content')
<div class="section-body">
    <div class="section-header">
        <h1>Products</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="{{ route('product.index') }}">Product</a></div>
            <div class="breadcrumb-item active"><a>Edit Product</a></div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>Edit Product</h4>
                </div>
                <form action="{{ route('product.update',$product->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                    <div class="card-body">
                        <div class="gambar">
                            <center>
                                <img src="{{ asset('storage/products/'.$product->image) }}" width="350px">
                            </center>
                        </div>
                        <div class="form-group row my-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Category</label>
                            <div class="col-sm-12 col-md-7">
                                <select name="category" class="form-control selectric">
                                    <option value="">--Select Category--</option>
                                    @foreach ($categories as $category)
                                    <option value="{{ $category->id }}"
                                        {{(($product->categories_id==$category->id)? 'selected':'')}}>
                                        {{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama Product</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="text" name="name" class="form-control" value="{{ $product->name }}">
                                @error('name')
                                <div class="bg-red-400 p-2 shadow-sm rounded mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Gambar Product</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="file" name="image" class="form-control" value="{{ $product->image }}">
                                @error('image')
                                <div class="bg-red-400 p-2 shadow-sm rounded mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Harga Product</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="text" name="price" class="form-control" value="{{ $product->price }}">
                                @error('price')
                                <div class="bg-red-400 p-2 shadow-sm rounded mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Deskripsi
                                Product</label>
                            <div class="col-sm-12 col-md-7">
                                <textarea name="description" class="form-control">{{ $product->description }}</textarea>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Status</label>
                            <label class="custom-switch mt-2">
                                <input type="checkbox" checked name="status" class="custom-switch-input"
                                    {{ $product->status == 'ready' ? 'checked' : '' }}>
                                <span class="custom-switch-indicator"></span>
                                <span class="custom-switch-description">Product Tersedia!!</span>
                            </label>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tampikan</label>
                            <label class="custom-switch mt-2">
                                <input type="checkbox" checked name="show" class="custom-switch-input"
                                    {{ $product->show == 'ya' ? 'checked' : '' }}>
                                <span class="custom-switch-indicator"></span>
                                <span class="custom-switch-description">Product Ditampilkan!!</span>
                            </label>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <a href="{{ route('product.index') }}" class="btn btn-danger">Cancel</a>
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')
@section('title','index | products')
@section('content')
<div class="section-body">
    <div class="section-header">
        <h1>Products</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="#">Products</a></div>
            <div class="breadcrumb-item"><a>Index</a></div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>Products List</h4>
                    <div class="card-header-action">
                        <a href="{{ route('product.create') }}" class="btn btn-primary">Tambah Data</a>
                    </div>
                </div>
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table table-striped mb-0 ">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Image</th>
                                    <th>Price</th>
                                    <th>Status</th>
                                    <th>Show</th>
                                    <th>Description</th>
                                    <th style="text-align: center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($products as $product )
                                <tr>
                                    <td width="150px">{{ $product->name }}</td>
                                    <td width="200px"><img src="{{ asset('storage/products/'.$product->image) }}" width="200px"
                                            class="w-48 rounded-md"></td>
                                    <td>{{ $product->price }}</td>
                                    <td>{{ $product->status }}</td>
                                    <td>{{ $product->show }}</td>
                                    <td width="200px">{{ $product->description }}</td>
                                    <td style="text-align: center">
                                        
                                        <form action="{{ route('product.destroy',$product->id) }}" method="POST">
                                            <a href="{{ route ('product.edit' , $product->id) }}"
                                                class="btn btn-primary btn-action mr-1" data-toggle="tooltip"
                                                title="Edit"><i class="fas fa-pencil-alt"></i></a>
                                            @csrf
                                            @method('DELETE')

                                            <button type="submit"
                                                class="btn btn-danger btn-action mr-1"
                                                onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')" ><i title="Hapus" class="fas fa-trash"></i></button>
                                        </form>
                                       
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/tambah.blade.php
@extends('layouts.app')
@section('title','Products | Tambah')
@section('content')
<div class="section-body">
    <div class="section-header">
        <h1>Products</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="{{ route('product.index') }}">Product</a></div>
            <div class="breadcrumb-item active"><a>Tambah Product</a></div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>Tambah Product</h4>
                </div>
                <form action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="card-body">
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Category</label>
                            <div class="col-sm-12 col-md-7">
                                <select name="category"
                                    class="form-control selectric @error('name') is-invalid @enderror">
                                    @error('category')
                                    <div class="invalid-feedback p-2 shadow-sm rounded mt-2">
                                        {{ $message }}
                                    </div>
                                    @enderror
                            </div>
                            <option value="">--Select Category--</option>
                            @foreach ($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama Product</label>
                        <div class="col-sm-12 col-md-7">
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror">
                            @error('name')
                            <div class="invalid-feedback p-2 shadow-sm rounded mt-2">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Gambar Product</label>
                        <div class="col-sm-12 col-md-7">
                            <input type="file" name="image" class="form-control @error('image') is-invalid @enderror"
                                id="formFileMultiple">
                            @error('image')
                            <div class="invalid-feedback shadow-sm rounded mt-2">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Harga Product</label>
                        <div class="col-sm-12 col-md-7">
                            <input type="text" name="price" class="form-control @error('price') is-invalid @enderror">
                            @error('price')
                            <div class="invalid-feedback shadow-sm rounded mt-2">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Deskripsi
                            Product</label>
                        <div class="col-sm-12 col-md-7">
                            <textarea name="description"
                                class="form-control @error('description') is-invalid @enderror"></textarea>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Status</label>
                        <label class="custom-switch mt-2">
                            <input type="checkbox" checked name="status" class="custom-switch-input">
                            <span class="custom-switch-indicator"></span>
                            <span class="custom-switch-description">Product Tersedia!!</span>
                        </label>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tampikan</label>
                        <label class="custom-switch mt-2">
                            <input type="checkbox" checked name="show" class="custom-switch-input">
                            <span class="custom-switch-indicator"></span>
                            <span class="custom-switch-description">Product Ditampilkan!!</span>
                        </label>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                        <div class="col-sm-12 col-md-7">
                            <a href="{{ route('product.index') }}" class="btn btn-danger">Cancel</a>
                            <button type="submit" class="btn btn-primary">Publish</button>
                        </div>
                    </div>
            </div>
            </form>
        </div>
    </div>
</div>
</div>
@endsection