routes/web.php
<?php

use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PenjualanController;
use App\Http\Controllers\PembelianController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TransaksiController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('Dashboard');
});

Route::resource('product', 'ProductController');
Route::resource('category', 'CategoryController');

Route::get('/discount', 'DiscountController@index');
Route::get('/discount/create', 'DiscountController@create');
Route::post('/discount', 'DiscountController@store');
Route::get('/discount/{discount}/edit', 'DiscountController@edit');
Route::patch('/discount/{discount}', 'DiscountController@update');
Route::delete('/discount/{id}', 'DiscountController@delete');

Route::get('/order', 'OrderController@index');

Route::get('/penjualan', 'PenjualanController@index');

//Bagian Pembelian
Route::resource('pembelian', 'PembelianController');

// Bagian Laporan
Route::resource('laporan', 'LaporanController');

// Bagian User
Route::resource('user', 'UserController');


Route::get('/transaksi', 'TransaksiController@index');
Route::get('/transaksi/create', 'TransaksiController@create');
Route::post('/transaksi', 'TransaksiController@store');
Route::get('/transaksi/{transaksi}/edit', 'TransaksiController@edit');
Route::patch('/transaksi/{transaksi}', 'TransaksiController@update');
Route::delete('/transaksi/{id}', 'TransaksiController@delete');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>@yield('title')</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!-- CSS Libraries -->
    <link rel="stylesheet" href="{{asset('/node_modules/jqvmap/dist/jqvmap.min.css')}}">
    <link rel="stylesheet" href="{{asset('/node_modules/weathericons/css/weather-icons.min.css')}}">
    <link rel="stylesheet" href="{{asset('/node_modules/weathericons/css/weather-icons-wind.min.css')}}">
    <link rel="stylesheet" href="{{asset('/node_modules/summernote/dist/summernote-bs4.css')}}">
    <link rel="stylesheet" href="{{asset('/node_modules/summernote/dist/summernote-bs4.css')}}">
    <link rel="stylesheet" href="{{asset('/assets/plugin/sweetalert2/sweetalert2.min.css')}}">
    <link rel="stylesheet" href="{{asset('/assets/plugin/datatables/datatables.min.css')}}">
    <link rel="stylesheet" href="{{asset('/assets/plugin/datatables/select.bootstrap4.min.css')}}">
    <link rel="stylesheet" href="{{asset('/assets/plugin/datatables/dataTables.bootstrap4.min.css')}}">

    <!-- Template CSS -->
    <link rel="stylesheet" href="{{ asset('/assets/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('/assets/css/components.css') }}">


</head>

<body>
    <div class="main-wrapper" id="app">
        {{-- Add Nav --}}
        @include('layouts.nav')

        {{-- Add Sidebar --}}
        @include('layouts.sidebar')

        <!-- Main Content -->
        <div class="main-content">
            <section class="section">

                <div class="section-header">
                    <h1>@yield('heading')</h1>
                    <div class="section-header-breadcrumb">
                        <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                        <div class="breadcrumb-item">@yield('page')</div>
                    </div>
                </div>
                @yield('content')
            </section>
        </div>

        <footer class="main-footer">
            <div class="footer-left">
                Copyright &copy; 2018 <div class="bullet"></div> Design By <a href="https://nauval.in/">Muhamad
                    Nauval Azhar</a>
            </div>
            <div class="footer-right">
                2.3.0
            </div>
        </footer>
    </div>

    <!-- General JS Scripts -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="../assets/js/stisla.js"></script>

    <!-- JS Libraies -->
    <script src="{{asset('/node_modules/simpleweather/jquery.simpleWeather.min.js')}}"></script>
    <script src="{{asset('/node_modules/chart.js/dist/Chart.min.js')}}"></script>
    <script src="{{asset('/node_modules/jqvmap/dist/jquery.vmap.min.js')}}"></script>
    <script src="{{asset('/node_modules/jqvmap/dist/maps/jquery.vmap.world.js')}}"></script>
    <script src="{{asset('/node_modules/summernote/dist/summernote-bs4.js')}}"></script>
    <script src="{{asset('/node_modules/chocolat/dist/js/jquery.chocolat.min.js')}}"></script>
    <script src="{{asset('/assets/plugin/sweetalert2/sweetalert2.min.js')}}"></script>
    <script src="{{asset('/assets/plugin/datatables/datatables.min.js')}}"></script>
    <script src="{{asset('/assets/plugin/datatables/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('/assets/plugin/datatables/dataTables.select.min.js')}}"></script>
    <script src="{{asset('/assets/plugin/datatables/jquery-ui.min.js')}}"></script>

    <!-- Template JS File -->
    <script src="{{asset('/assets/js/scripts.js')}}"></script>
    <script src="{{asset('/assets/js/custom.js')}}"></script>

    <!-- Page Specific JS File -->
    <script src="{{asset('/assets/js/page/index-0.js')}}"></script>
    <script src="{{asset('/assets/plugin/datatables/modules-datatables.js')}}"></script>
    @stack('scripts')

</body>

</html>

resources/views/layouts/nav.blade.php
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg bg-primary">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a>
            </li>
        </ul>
    </form>
    <ul class="navbar-nav navbar-right">
        <li class=""><a
                class="nav-link nav-link-lg nav-link-user">
                <div class="d-sm-none d-lg-inline-block">Hi, Welcome to My Note</div>
            </a>
        </li>
    </ul>
</nav>

resources/views/layouts/sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="#">Goshop</a>

            <a href="index.html">GOShop</a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="index.html">GS</a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">Admin Mode</li>
            <li class="nav-item active">
                <a href="{{ url('/') }}" class="nav-link"><i class="fas fa-fire"></i><span>Dashboard</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link has-dropdown" href="{{ route('product.index') }}" data-toggle="dropdown"><i
                        class="fab fa-product-hunt"></i>
                    <span>Products</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('product.index') }}"><span>Products Index</span></a></li>
                    <li><a class="nav-link" href="{{ route('product.create') }}"><span>Create Products</span></a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link has-dropdown" href="{{ route('category.index') }}" data-toggle="dropdown"><i
                        class="fas fa-th-large"></i>
                    <span>Category</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('category.index') }}"><span>Category Index</span></a></li>
                    <li><a class="nav-link" href="{{ route('category.create') }}"><span>Create Category</span></a></li>
                </ul>
            </li>

            <li class="nav-item">
                <a href="{{ url('/discount') }}" class="nav-link "><i class="fas fa-tags"></i><span>Discount</span></a>
            </li>
            <li class="nav-item">
                <a href="{{ url('/order') }}" class="nav-link "><i class="fas fa-archive"></i><span>Order</span></a>
            </li>
            <li class="nav-item">
                <a href="{{ url('/transaksi') }}" class="nav-link "><i class="fas fa-money-bill"></i><span>Transaksi</span></a>
            </li>
            <li class="nav-item">
                <a href="{{ url('/penjualan') }}" class="nav-link "><i class="fas fa-shopping-bag"></i><span>Penjualan</span></a>
            </li>
            <li class="nav-item dropdown">
                <a href="{{ route('pembelian.index') }}" class="nav-link has-dropdown"><i class="fas fa-shopping-cart"></i>
                <span>Pembelian</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('pembelian.index') }}"><span>Data Pembelian</span></a></li>
                    <li><a class="nav-link" href="{{ route('pembelian.create') }}"><span>Tambah Data Pembelian</span></a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a href="{{ route('laporan.index') }}" class="nav-link "><i class="fas fa-book"></i><span>Laporan</span></a>
            </li>
            <li class="nav-item dropdown">
                <a href="{{ route('user.index') }}" class="nav-link has-dropdown"><i class="fas fa-users"></i>
                <span>User</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('user.index') }}"><span>List User</span></a></li>
                    <li><a class="nav-link" href="{{ route('user.create') }}"><span>Add User</span></a></li>
                </ul>
            </li>
           
        </ul>
    </aside>
</div>